blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/mattintech/adbhelper/discussions/categories/q-a
    about: Please ask and answer questions in the Discussions Q&A section
  - name: Feature Discussions
    url: https://github.com/mattintech/adbhelper/discussions/categories/ideas
    about: Discuss feature ideas before creating a feature request issue
  - name: Show and Tell
    url: https://github.com/mattintech/adbhelper/discussions/categories/show-and-tell
    about: Share your creative uses of ADB Helper with the community